ArabicWorkersMangement/Models/Employee.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
namespace ArabicWorkersMangement.Models
{
    public class Employee
    {
        public int ID { get; set; }
        [Required]
        [StringLength(255)]
        public string Name { get; set; }
        [Required]
        public double SalaryPerHour { get; set; }
        [StringLength(25)]
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public IList<Day> WorkedDays { get; set; }
        public Employee()
        {
            WorkedDays = new List<Day>();
        }
    }
}

ArabicWorkersMangement/Controllers/DayController.cs
using ArabicWorkersMangement.Models;
using ArabicWorkersMangement.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace ArabicWorkersMangement.Controllers
{
    public class DayController : Controller
    {
        private ApplicationDbContext context;

        public DayController()
        {
            context = new ApplicationDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            context.Dispose();
        }
        [Route("day/create/{EmployeeID}")]
        public ActionResult Create(int employeeId)
        {
            var today = DateTime.Today;
            var newDay = new DayViewModel()
            {
                DayId = 0,
                EmployeeId = employeeId,
                DayDate = today,
                ShiftStartingTime = new DateTime(today.Year, today.Month, today.Day, 9, 0, 0),
                ShiftEndingTime = new DateTime(today.Year, today.Month, today.Day, 19, 0, 0)
            };
            return View("DayForm", newDay);
        }

        [Route("day/edit/{dayId}")]
        public ActionResult Edit(int dayId)
        {
            try
            {
                var dayInDb = context.Days.Include(c => c.Employee).Where(x => x.Id == dayId).First();
                var editDay = new DayViewModel()
                {
                    DayId = dayInDb.Id,
                    EmployeeId = dayInDb.Employee.ID,
                    DayDate = dayInDb.Start.Date,
                    ShiftStartingTime = dayInDb.Start,
                    ShiftEndingTime = dayInDb.End
                };
                return View("DayForm", editDay);
            }
            catch
            {
                return RedirectToAction("Index", "Employee");
            }
        }
        [HttpPost]
        public ActionResult Save(DayViewModel day)
        {
            if (day.ShiftStartingTime >= day.ShiftEndingTime)
                return RedirectToAction("details", "Employee", new { id = day.EmployeeId });

            if (day.DayId == 0)
            {
                var newDay = new Day()
                {
                    Employee = context.Employees.First(x => x.ID == day.EmployeeId),
                    Start = SettingTime(day.DayDate, day.ShiftStartingTime),
                    End = SettingTime(day.DayDate, day.ShiftEndingTime)
                };
                newDay.DayDuration = (newDay.End - newDay.Start).TotalHours;
                context.Days.Add(newDay);
            }
            else
            {
                var dayInDb = context.Days.Include(c => c.Employee).Where(x => x.Id == day.DayId).First();
                dayInDb.Start = SettingTime(day.DayDate, day.ShiftStartingTime);
                dayInDb.End = SettingTime(day.DayDate, day.ShiftEndingTime);
                dayInDb.DayDuration = (dayInDb.End - dayInDb.Start).TotalHours;
            }
            context.SaveChanges();
            return RedirectToAction("details", "Employee", new { id = day.EmployeeId });
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var day = context.Days.Include(c => c.Employee).SingleOrDefault(c => c.Id == id);
            var employeeId = day.Employee.ID;
            context.Days.Remove(day);
            context.SaveChanges();
            return RedirectToAction("details", "Employee", new { id = employeeId });
        }
        private DateTime SettingTime(DateTime date, DateTime time)
        {
            return new DateTime(date.Year, date.Month, date.Day, time.Hour, time.Minute, 00);
        }
    }
}

ArabicWorkersMangement/Controllers/EmployeeController.cs
using ArabicWorkersMangement.Models;
using ArabicWorkersMangement.ViewModels;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ArabicWorkersMangement.Controllers
{
    public class EmployeeController : Controller
    {
        private ApplicationDbContext context;

        public EmployeeController()
        {
            context = new ApplicationDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            context.Dispose();
        }
        [Route("employees")]
        public ActionResult Index()
        {
            var employees = context.Employees.OrderBy(x => x.Name).ToList();
            return View(employees);
        }
        [Route("employee/new")]
        public ActionResult New()
        {

            return View();
        }
        [HttpPost]
        public ActionResult Save(Employee employee)
        {
            if (employee.Name == null)
                return RedirectToAction("new", "Employee");

            if (employee.ID == 0)
            {
                context.Employees.Add(employee);
            }
            else
            {
                var employeeInDB = context.Employees.Single(x => x.ID == employee.ID);

                employeeInDB.Name = employee.Name;
                employeeInDB.SalaryPerHour = employee.SalaryPerHour;
                employeeInDB.PhoneNumber = employee.PhoneNumber;
                employeeInDB.Address = employee.Address;
            }
            context.SaveChanges();
            return RedirectToAction("Index", "Employee");
        }
        [Route("employee/details/{id}")]
        public ActionResult Details(int id)
        {
            var employeeInDb = context.Employees.SingleOrDefault(c => c.ID == id);
            if (employeeInDb == null)
                return HttpNotFound();
            var EmployeeAndDays = new EmployeeDaysViewModel()
            {
                Employee = employeeInDb,

                Days = context.Days.Where(c => c.Employee.ID == id)
                .OrderByDescending(x => x.Start).Take(100).ToList(),

                WeekHours = context.Days.ToList()
               .Where(x => x.Employee.ID == id)
               .GroupBy(g => (CultureInfo.CurrentCulture.Calendar
                .GetWeekOfYear(g.Start.Date, CalendarWeekRule.FirstDay, DayOfWeek.Saturday)))
                .Select(z => new
                {
                    WeekNumber = z.Key,
                    WeekFirstDayDublicate = z.Min
                    (c => c.Start.AddDays(-1 * (7 + (c.Start.DayOfWeek - DayOfWeek.Saturday)) % 7)),
                    TotalHours = z.Sum(c => c.DayDuration),
                })
                .GroupBy(z => z.WeekFirstDayDublicate)
                .Select(z => new WeekHoursViewModel
                {
                    WeekFirstDay = z.Key,
                    TotalHours = z.Sum(c => c.TotalHours)
                })
                .OrderByDescending(z => z.WeekFirstDay).Take(5)
            };
            return View(EmployeeAndDays);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var employee = context.Employees.SingleOrDefault(c => c.ID == id);
            var days = context.Days.Where(x => x.Employee.ID == id).ToList();

            foreach (var day in days)
            {
                context.Days.Remove(day);
            }
            context.Employees.Remove(employee);
            context.SaveChanges();
            return RedirectToAction("Index", "Employee");
        }
    }
}

ArabicWorkersMangement/Views/Employee/Details.cshtml
@model ArabicWorkersMangement.ViewModels.EmployeeDaysViewModel

@{
    ViewBag.Title = Model.Employee.Name;
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>@Model.Employee.Name</h2>
@using (Html.BeginForm("save", "Employee"))
{
    <div class="employee">
        <div class="form-group">
            <label>الاسم</label>
            @Html.TextBoxFor(m => m.Employee.Name, new { @class = "form-control" })
        </div>
        <div class="form-group">
            <label>تكلفة الساعة</label>
            @Html.TextBoxFor(c => c.Employee.SalaryPerHour, new { @class = "form-control" })
        </div>
    </div>
    <div class="employee">
        <div class="form-group">
            <label>رقم الهاتف</label>
            @Html.TextBoxFor(c => c.Employee.PhoneNumber, new { @class = "form-control" })
        </div>
        <div class="form-group">
            <label>العنوان</label>
            @Html.TextBoxFor(c => c.Employee.Address, new { @class = "form-control" })
        </div>
    </div>
    @Html.HiddenFor(e => e.Employee.ID)
    <button type="submit" class="btn btn-primary">حفظ</button>
}
<hr />
@if (!Model.Days.Any())
{
    <input type="button" value="يوم جديد" class="btn btn-primary" onclick="location.href='@Url.Action("Create", "Day",new { id = Model.Employee.ID }, null)'" />
    <br />
    <br />
    <p>لايوجد أيام سابقة </p>
}
else
{
    <h2>اخر 5 اسابيع</h2>
    <table class="table table-bordered table-hover">
        <thead class="text-right">
            <tr>

                <th class="not_mapped_style" style="text-align:right">الاسبوع</th>
                <th class="not_mapped_style" style="text-align:right">عدد الساعات</th>
                <th class="not_mapped_style" style="text-align:right">مستحقات الأسبوع</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.WeekHours)
            {
                <tr>
                    <td>@item.WeekFirstDay.ToString("dddd dd-MMM-yyyy", new System.Globalization.CultureInfo("ar-AE"))</td>
                    <td>@item.TotalHours</td>
                    <td>@(@item.TotalHours * @Model.Employee.SalaryPerHour)</td>
                </tr>
            }
        </tbody>
    </table>
    <hr />
    <input type="button" value="يوم جديد" class="btn btn-primary" onclick="location.href='@Url.Action("Create", "Day",new { id = Model.Employee.ID }, null)'" />
    <br />
    <br />
    <table id="days" class="table table-bordered table-hover">
        <thead class="text-right">
            <tr>

                <th class="not_mapped_style" style="text-align:right">اليوم</th>
                <th class="not_mapped_style" style="text-align:right">حضور</th>
                <th class="not_mapped_style" style="text-align:right">انصراف</th>
                <th class="not_mapped_style" style="text-align:right">المدة</th>
                <th class="not_mapped_style" style="text-align:right">حذف</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var day in Model.Days)
            {
                <tr>

                    <td>
                        @Html.ActionLink(day.Start.ToString("dddd dd-MMM-yyyy", new System.Globalization.CultureInfo("ar-AE")), "Edit", "Day", new { id = day.Id }, null)
                    </td>
                    <td>@day.Start.ToString("HH:mm")</td>
                    <td>@day.End.ToString("HH:mm")</td>
                    <td>@day.DayDuration</td>
                    <td>
                        <button data-day-id="@day.Id" class="btn-link js-delete">حذف</button>
                    </td>

                </tr>
            }
        </tbody>
    </table>
}

@section scripts
{
    <script>
        $(document).ready(function () {
            $("#days").DataTable({
                "ordering": false
            });
            $("#days .js-delete").on("click", function () {
                if (confirm("هل ترغب فى حذف هذا اليوم؟؟")) {
                    $.ajax({
                        url: "/day/delete/" + $(this).attr("data-day-id"),
                        method: "POST",
                        success: function () {
                            location.reload(true);
                        }
                    });
                }
            });
        });
    </script>
}
<style type="text/css">
    .employee div {
        display: inline-block;
        width: 500px;
        min-height: 50px;
        height: auto;
    }
</style>

ArabicWorkersMangement/Views/Employee/Index.cshtml
@model IEnumerable<ArabicWorkersMangement.Models.Employee>
@{
    ViewBag.Title = "العمال";
}
<h2>العمال</h2>
<br />
<input type="button" value="اضافة عامل" class="btn btn-primary" onclick="location.href='@Url.Action("new", "employee")'" />

@if (!Model.Any())
{
    <br />
    <br />
    <p>لايوجد عاملين</p>
}
else
{
    <br />
    <br />
    <table id="employees" class="table table-bordered table-hover">
        <thead>
            <tr>
                <th class="not_mapped_style" style="text-align:right">الأسم</th>
                <th class="not_mapped_style" style="text-align:right">حساب الساعة</th>
                <th class="not_mapped_style" style="text-align:right">حذف</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var employee in Model)
            {
                <tr>
                    <td>@Html.ActionLink(employee.Name, "details", "Employee", new { id = employee.ID }, null)</td>
                    <td>@employee.SalaryPerHour</td>
                    <td>
                        <button data-employee-id="@employee.ID" class="btn-link js-delete">حذف</button>
                    </td>

                </tr>
            }
        </tbody>
    </table>
}
@section scripts
{
    <script>
        $(document).ready(function () {
            $("#employees").DataTable();

            $("#employees .js-delete").on("click", function () {
                if (confirm("هل ترغب فى حذف هذا العامل؟؟")) {
                    $.ajax({
                        url: "/employee/delete/" + $(this).attr("data-employee-id"),
                        method: "POST",
                        success: function () {
                            location.reload(true);
                        }
                    });
                }
            });
        });
    </script>
}

ArabicWorkersMangement/Views/Employee/New.cshtml
@model ArabicWorkersMangement.Models.Employee
@{
    ViewBag.Title = "جديد";
}

<h2>عامل جديد</h2>
@using (Html.BeginForm("save", "Employee"))
{
    <div class="container-name">
        <div class="form-group">
            <label>الاسم</label>
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        </div>
        <div class="form-group">
            <label>تكلفة الساعة</label>
            @Html.TextBoxFor(c => c.SalaryPerHour, new { @class = "form-control" })
        </div>
    </div>
    <div class="container-name">
        <div class="form-group">
            <label>رقم الهاتف</label>
            @Html.TextBoxFor(c => c.PhoneNumber, new { @class = "form-control" })
        </div>
        <div class="form-group">
            <label>العنوان</label>
            @Html.TextBoxFor(c => c.Address, new { @class = "form-control" })
        </div>
    </div>
    <button type="submit" class="btn btn-primary">حفظ</button>
}

<style type="text/css">
    .container-name div {
        display: inline-block;
        width: 500px;
        min-height: 50px;
        height: auto;
    }
</style>